### ISSUE TITLE
如何使用chatglm-6b-int4量化后的模型

### ISSUE THREAD

**Issue by abigkeep** [hasban12138/SaturdayAI#1]
如何使用chatglm-6b-int4量化后的模型，想节约显存

**Comment by hasban12138** [comment]
```
def prepare_model():
    global model
    model = model.half().quantize(4).cuda()
    model = model.eval()
```
此处已经量化成int4了
如果想用的话可以参考这个清华的教程 [低成本部署]( https://github.com/THUDM/ChatGLM-6B#%E4%BD%8E%E6%88%90%E6%9C%AC%E9%83%A8%E7%BD%B2)

**Comment by hasban12138** [comment]
没有回复的话 我就关了
